
#ifndef SOURCE_01_MCAL_ADC_INC_ADC_TYPES_H_
#define SOURCE_01_MCAL_ADC_INC_ADC_TYPES_H_

typedef enum{
	ADC_CHNL0,
	ADC_CHNL1,
	ADC_CHNL2,
	ADC_CHNL3,
	ADC_CHNL4,
	ADC_CHNL5,
	ADC_CHNL6,
	ADC_CHNL7
}adc_Channel_t;

#endif /* SOURCE_01_MCAL_ADC_INC_ADC_TYPES_H_ */

